local _, Flame = ...
Flame.misc = {
  -- Classes  
  ["术士"] = "Warlock",
  ["战士"] = "Warrior",
  ["猎人"] = "Hunter",
  ["法师"] = "Mage",
  ["牧师"] = "Priest",
  ["德鲁伊"] = "Druid",
  ["圣骑士"] = "Paladin",
  ["萨满祭司"] = "Shaman",
  ["盗贼"] = "Rogue",
  ["QS"] = "Paladin",
  ["XD"] = "Druid",
  ["LR"] = "Hunter",
  ["FS"] = "Mage",
  ["DZ"] = "Rogue",
  ["SM"] = "Shaman",
  ["SS"] = "Warlock",
  ["ZS"] = "Warrior",
  ["MS"] = "Priest",
  -- Dungeons
  ['NY']='RFC',
  ['AH']='WC',
  ['YY']='SFK',
  ['MD']='MARAUDON',
  ['怒焰']='RFC',
  ['怒焰裂谷']='RFC',
  ['哀嚎洞穴']='WC',
  ['死亡矿坑']='DM',
  ['影牙城堡']='SFK',
  ['黑暗深渊']='BFD',
  ['暴风监狱']='STOCKADES',
  ['剃刀沼泽']='RFK',
  ['诺莫瑞根']='GNOMER',
  ['剃刀高地']='RFD',
  ['血色修道院']='SM',
  ['血色']='SM',
  ['教堂']='Cathedral',
  ['墓地']='Graveyard',
  ['奥达曼']='ULDAMAN',
  ['祖尔法拉克']='ZF',
  ['玛拉顿']='MARAUDON',
  ['塔哈克神庙']='ST',
  ['黑石深渊']='BRD',
  ['本通灵学院']='SCHOLO',
  ['斯坦索姆']='STRAT',
  ['黑石塔下']='LBRS',
  ['黑石塔上']='UBRS',
  ['厄运之槌']='DM',
  -- Role
  ['坦克']='tank',
  ['治疗']='healer',
  ['奶妈']='healer',
  ['摔绊']='melee',
  ['奥术射击']='ranged',
  --
  ['M']='whisper',
  ['JY']='elite',
  ['任务']='quest',
  ['=']='wait',
}